server:
  error:
    include-message: always
  port: 3000

logging:
  file:
    name: logs.log
  logback:
    rollingpolicy:
      max-file-size: 100MB

spring:
  application:
    name: SimpleBanking
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          import_files:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:simplebanking}
    username: ${POSTGRES_NAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}


security:
  cors-ip: 'localhost:${server.port}}'
jwt:
  duration: 86400
